spring:
  datasource:
    url: jdbc:mysql://3.36.50.217/apitest
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  tomcat:
    mbeanregistry:
      enabled: true

# ?????? ??
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
